travis:
  secure:
    BINSTAR_TOKEN: RiHlzq4KnZYSGBPb+n2wmjtwGh1Mb4mRGMceZg30tNxk/w87+Vozv4QYyxC/DDotfx9fxeXIC2MF5YJUZXIiyxr/PJZwwkZvZICL4RgADWPzw/UnOIURn+AjU6dSed2IsLqEO3Xa3IfroRMaR70qORgxUPlXfbH2qaeW5qiXfqDt7Eo3bTlLaHd94w0yCBViy8VVxpmigOu0fued8cjnhEcNnO1EYRF1JIM8RQccRxHnrzfRBXglVYVcqfV3g6gpz/WQWqJyBYT0HdQ3OPfG6q12j/4RyhQV7RswU6zOPCWcvFRq8ag/rl6pDYVl4PQcBDuEpoNupM4KaL+2xt+JIGKD85H3zMGbvnvQezirqUAnRjzM9U+jrJw+WvQiBxJovyPRTM5tsCoNgK6Ij/T2BIOSgNVUdUq9jsKO/c2gSd7PQGXy8O5vu067KIMkOzTpAupgcazVVBcsHhBYnv7cPHPLwLkAA6bLLiqSNCobnf3QwzLDM99/YIqljrQdIdpCL1zFysEBXiHSDqmpNOtuYOb7wrNYyI9qhLnv7l8JV661rmz/bkl2ipfEAByU1qEqJZHF5LyyvvIJldDh0vlTTrSxvCY3RD2vCgqjd6MSZhjjeC+thGvotsflHawZVy4h1c/ktVkcosZ4DEje9vgQofOJ1B1uW/0lWfGQB0yNR2I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
